import Link from "next/link";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "My website",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          <Link href="/post/hello">Hello</Link>
          <Link href="/post/goodbye">Goodbye</Link>
        </nav>
        <Script id="log">{`console.log("test")`}</Script>
        {children}
      </body>
    </html>
  );
}
